### ISSUE TITLE
access the dot display buffer before animation ?

### ISSUE THREAD

**Issue by woeperbe** [MajicDesigns/MD_Parola#123]
Hello,
i would like to insert in the display buffer just before the animation my own bit pattern.
Is there any method to obtain this ?
The picture show what i would like to insert in the buffer 
![Graph](https://github.com/MajicDesigns/MD_Parola/assets/45015193/4e220d30-d40d-4f50-8f98-c6d9a5dc7951)

**Comment by MajicDesigns** [comment]
Please read the response to issue #114.

**Comment by woeperbe** [comment]
That doesn't answer my question.
I need to be able to animate the display with my own bit pattern as in the picture ...

**Comment by MajicDesigns** [comment]
It does answer the question "i would like to insert in the display buffer just before the animation my own bit pattern" - you use getGraphicObject() and use the MD_MAX72xx function to draw the graphic you want. If you now want to animate just this 'graphic' you will do it your code, as Parol will have no knowledge of this extra stuff on the display.

Without knowing the details of what you are trying to do I cannot suggest much more specific solution. Maybe describe what you are trying to do rather than the solution you think you need.

**Comment by woeperbe** [comment]
I will try this today
Thanks for your beautifull library and the support at wrapspeed
Happy new-year
Greetings,
Marc Buffet


On Jan 2, 2024, at 04:16, Marco Colli ***@***.***> wrote:

﻿

It does answer the question "i would like to insert in the display buffer just before the animation my own bit pattern" - you use getGraphicObject() and use the MD_MAX72xx function to draw the graphic you want. If you now want to animate just this 'graphic' you will do it your code, as Parol will have no knowledge of this extra stuff on the display.

Without knowing the details of what you are trying to do I cannot suggest much more specific solution. Maybe describe what you are trying to do rather than the solution you think you need.
