### ISSUE TITLE
Scrolling starting with no effect

### ISSUE THREAD

**Issue by davidglass38** [MajicDesigns/MD_Parola#86]
Hello,
Thank you for this great library
When I do this :
myDisplay.displayText(buf_MAX7219, PA_LEFT, SPEED, 0, PA_NO_EFFECT, PA_SCROLL_LEFT);
the text display correctly at first frame, starting from the left.
But when srolling starts at second frame to show the next part of text, only empty columns are showing.
What am I doing wrong ?
This shows the full text, but it's not the effect I want as at first frame the screen is entirely black.
myDisplay.displayText(buf_MAX7219, PA_LEFT, SPEED, 0, PA_SCROLL_LEFT, PA_SCROLL_LEFT);
Thank you !

**Comment by MajicDesigns** [comment]
This happens because the in the design of the scrolling effects, a text is scrolled IN until the end of the text is reached (whether to the left or the right). So when the text is scrolled OUT, the assumption is that it is already at the end of the text and it fills the display with empty columns.

Technically, it is working as designed, so it is not a bug. I cannot see any easy way to fix this, so I will mark it as no-fix and just say that this combination of text effects will not produce the expected result for text longer than the display size.

**Comment by davidglass38** [comment]
Thank you for your answer.
